// template-data.js — 80 High-Converting Proposal Templates (10 per category)

const TEMPLATE_DATA = {

webdev: [
  { name:"Bold Opener", tag:"🔥 Direct", intro:"I won't waste your time with a generic pitch. I've built 20+ websites just like this one, and I know exactly what it takes to deliver fast.", price:"$350", hook:"Let's skip the back-and-forth. You need results, not promises." },
  { name:"Pain Point Hook", tag:"😣 Empathy", intro:"I know how frustrating it is to hire developers who disappear after the deposit. That won't happen here — I deliver on time, every time.", price:"$380", hook:"What specific problem is your current website failing to solve?" },
  { name:"Social Proof", tag:"📊 Results", intro:"My last 3 clients saw a 40% increase in conversions after launch. I build websites that don't just look great — they perform.", price:"$420", hook:"Want me to show you a recent project with similar requirements?" },
  { name:"Question Hook", tag:"❓ Curiosity", intro:"What if your website could load in under 2 seconds AND rank on Google page 1? That's exactly what I specialize in building.", price:"$390", hook:"What does your ideal website feel like to a visitor in the first 3 seconds?" },
  { name:"Process Expert", tag:"⚙️ Methodology", intro:"My 6-step web development process ensures zero surprises: Discovery → Wireframe → Design → Development → Testing → Launch. You're involved at every stage.", price:"$400", hook:"Can I share a quick wireframe idea based on your requirements?" },
  { name:"Quick Win", tag:"⚡ Fast", intro:"I can have your first working prototype ready within 48 hours. You'll see real progress before you even finish your coffee tomorrow.", price:"$340", hook:"Want to see a rough mockup of your homepage by tomorrow?" },
  { name:"Value Stack", tag:"💎 Premium", intro:"When you invest in a professionally built website, you get: more leads, higher trust, better Google rankings, and a competitive edge. I deliver all four.", price:"$450", hook:"How much is a single new client worth to your business?" },
  { name:"Empathy First", tag:"🤝 Trust", intro:"I read your job post twice. I understand what you need — not just technically, but what this website means for your business goals.", price:"$370", hook:"I'd love to understand your vision before I even start coding." },
  { name:"Challenger", tag:"🎯 Bold", intro:"Most web developers will just build what you ask for. I'll ask WHY you want it, because sometimes the solution is different — and better.", price:"$410", hook:"What's the single most important action you want visitors to take?" },
  { name:"Story Teller", tag:"📖 Narrative", intro:"6 months ago, a client came to me with a broken website losing $2k/month in leads. Today it's their best sales tool. I'd love to do the same for you.", price:"$395", hook:"Where do you see your website taking your business in 12 months?" }
],

seo: [
  { name:"Data Driven", tag:"📊 Analytics", intro:"I ran a quick analysis of your niche. Your top 3 competitors have 200+ backlinks to pages you don't even have yet. I can fix that.", price:"$299/mo", hook:"Want me to share the keyword gap analysis I did for your site?" },
  { name:"Pain Point Hook", tag:"😣 Empathy", intro:"If your website isn't on page 1, it's essentially invisible. 93% of clicks go to the first page. Let's get you there — permanently.", price:"$249/mo", hook:"What keywords do you most want to rank for right now?" },
  { name:"Bold ROI", tag:"💰 ROI", intro:"SEO isn't a cost — it's the highest-ROI marketing channel available. Every $1 spent on organic search returns $22 on average. Let me show you the math.", price:"$349/mo", hook:"How much traffic would you need to justify this investment?" },
  { name:"Quick Win", tag:"⚡ Fast", intro:"In the first 30 days, I focus on the 3 technical fixes that have the biggest immediate ranking impact. You'll see movement before Month 2.", price:"$279/mo", hook:"Have you run a technical SEO audit in the last 6 months?" },
  { name:"Social Proof", tag:"🏆 Proven", intro:"I took a Shopify store from 200 to 8,000 monthly visitors in 4 months. Zero paid ads. All organic. Same strategy applies here.", price:"$319/mo", hook:"Want to see the exact strategy I used with screenshots?" },
  { name:"Process Expert", tag:"⚙️ Method", intro:"Month 1: Technical SEO. Month 2: On-page optimization. Month 3: Authority building. This isn't guesswork — it's a proven 90-day framework.", price:"$289/mo", hook:"Do you currently have a Google Search Console account set up?" },
  { name:"Empathy First", tag:"🤝 Trust", intro:"I know you've probably been burned by SEO agencies before who promised page 1 and delivered nothing. I work differently — transparent, honest, measurable.", price:"$269/mo", hook:"What was your biggest frustration with SEO services in the past?" },
  { name:"Niche Expert", tag:"🎯 Specialist", intro:"I don't do generic SEO. I specialize in your specific niche, which means I already know the keyword gaps, competitor weaknesses, and content angles that work.", price:"$329/mo", hook:"What's your primary product or service that you want to rank for?" },
  { name:"Content First", tag:"✍️ Content", intro:"SEO in 2024 is 70% content strategy. I build topical authority clusters that Google rewards with rankings that compound over time.", price:"$299/mo", hook:"Do you have a content calendar, or would you like me to build one?" },
  { name:"Local SEO", tag:"📍 Local", intro:"For local businesses, Google Maps ranking is more valuable than website ranking. I'll get you into the Local 3-Pack within 60 days.", price:"$199/mo", hook:"Is your Google Business Profile fully set up and verified?" }
],

writing: [
  { name:"Results Hook", tag:"📈 Results", intro:"The articles I write don't just sit on your blog — they rank on page 1 and bring you leads for years. Content is the gift that keeps giving.", price:"$45/article", hook:"What's the main conversion goal for your content?" },
  { name:"Pain Point", tag:"😣 Empathy", intro:"Bad content is worse than no content. It hurts your brand and wastes your budget. I write content that builds authority, not just fills pages.", price:"$50/article", hook:"What's the biggest content challenge you're facing right now?" },
  { name:"Speed Focus", tag:"⚡ Fast", intro:"You post a job, I research, write, and deliver a polished 1,500-word article within 24 hours. No follow-ups needed. Just great content.", price:"$40/article", hook:"How frequently do you need content published?" },
  { name:"SEO Writer", tag:"🔍 SEO", intro:"Every article I write is keyword-researched, structured with proper H1/H2/H3, and optimized for featured snippets. Rankings follow naturally.", price:"$55/article", hook:"Which target keyword do you most want this article to rank for?" },
  { name:"Brand Voice", tag:"🎤 Voice", intro:"I don't just write — I become your brand voice. After reading 3 of your existing articles, I'll match your tone so perfectly that readers won't know it changed.", price:"$48/article", hook:"Can you share 2-3 existing articles that represent your ideal voice?" },
  { name:"Social Proof", tag:"🏆 Proven", intro:"One of my articles generated 12,000 organic visits in 3 months for a SaaS client. The secret? It answered exactly what their audience was searching for.", price:"$60/article", hook:"Want to see a writing sample from the same niche as your project?" },
  { name:"Niche Expert", tag:"🎯 Expert", intro:"I don't write about everything. I specialize in [your niche], which means deep research, accurate facts, and content that builds real authority.", price:"$52/article", hook:"What level of technical depth does your target audience expect?" },
  { name:"Long Form", tag:"📄 Long-form", intro:"Long-form content (2,000+ words) gets 3x more backlinks and ranks for 6x more keywords. I write comprehensive guides that become your site's cornerstone pages.", price:"$75/article", hook:"Would you like an outline before I start writing?" },
  { name:"Conversion Copy", tag:"💰 Convert", intro:"Most content informs. Mine converts. I write articles with strategic CTAs, internal links, and reader psychology built in — to turn readers into customers.", price:"$65/article", hook:"What action do you want readers to take after finishing the article?" },
  { name:"Ghost Writer", tag:"🕵️ Ghost", intro:"You get the byline, I do the work. Full ghostwriting with your specific voice, opinions, and expertise — content that sounds exactly like you wrote it.", price:"$58/article", hook:"Would you like to do a 10-minute voice note call so I can capture your tone?" }
],

design: [
  { name:"Business Impact", tag:"💼 ROI", intro:"Good design isn't decoration — it's strategy. Companies with strong UI see 200% higher conversion rates. I design with that goal in mind.", price:"$500", hook:"What is the #1 action you want users to take on this product?" },
  { name:"User First", tag:"👤 UX", intro:"I start every project by asking: who is the user and what frustrates them? The best design solves real problems invisibly.", price:"$480", hook:"Do you have any user research or feedback I can start from?" },
  { name:"Social Proof", tag:"🏆 Track Record", intro:"My last app design reduced user drop-off by 35% in 2 months. Great UX isn't guesswork — it's research, testing, and iteration.", price:"$550", hook:"Would you like to see the case study with before/after metrics?" },
  { name:"Process Driven", tag:"⚙️ Method", intro:"Discovery → Wireframes → Visual Design → Prototype → Handoff. Every phase is structured so you know exactly what's happening and when.", price:"$520", hook:"Have you validated your core user flow with real users yet?" },
  { name:"Mobile First", tag:"📱 Mobile", intro:"70% of your users are on mobile. I design mobile-first, then scale up — ensuring the experience is perfect on every screen size.", price:"$460", hook:"What percentage of your current users are on mobile vs desktop?" },
  { name:"Brand Aligned", tag:"🎨 Branding", intro:"Your UI should feel like a natural extension of your brand — same colors, personality, and emotion. I'll make the product feel unmistakably yours.", price:"$490", hook:"Do you have existing brand guidelines I should work within?" },
  { name:"Quick Turnaround", tag:"⚡ Fast", intro:"You'll have a complete clickable prototype in 5 days. Developers can start building while you're still collecting stakeholder feedback.", price:"$440", hook:"What's your development start date? I'll work backward from there." },
  { name:"Conversion UI", tag:"💰 Conversion", intro:"I design landing pages and onboarding flows that convert. Every button, color, and layout decision is backed by conversion psychology.", price:"$510", hook:"What's your current sign-up or purchase conversion rate?" },
  { name:"Competitor Gap", tag:"🔍 Research", intro:"I'll audit your top 3 competitors' UX and identify exactly where you can do better. Then I'll design those improvements into your product.", price:"$530", hook:"Who are your top 2 competitors whose UI you want to outperform?" },
  { name:"Design System", tag:"🧱 Scalable", intro:"Instead of one-off screens, I'll build you a complete design system — components, tokens, and patterns your team can reuse forever.", price:"$650", hook:"Do you have a development team that needs Figma component handoff?" }
],

mobile: [
  { name:"Ship Fast", tag:"⚡ Fast", intro:"I've shipped 15 apps to the App Store and Play Store. My streamlined process gets you from wireframe to live app in 3 weeks, not 3 months.", price:"$1,200", hook:"What's your target launch date?" },
  { name:"User Retention", tag:"📊 Retention", intro:"An app that users download but don't open is worthless. I build apps with retention-focused UX: smart onboarding, push notifications, and habit-forming flows.", price:"$1,400", hook:"What will make users open your app every single day?" },
  { name:"Cross Platform", tag:"📱 Cross-Platform", intro:"One codebase. Both iOS and Android. React Native/Flutter saves you 60% vs building two separate native apps — without sacrificing quality.", price:"$1,100", hook:"Do you need both iOS and Android, or just one platform to start?" },
  { name:"Social Proof", tag:"🏆 Track Record", intro:"My last app reached #3 in its App Store category within 2 weeks of launch. Great apps need great strategy, not just great code.", price:"$1,500", hook:"Have you validated your app idea with target users yet?" },
  { name:"MVP Focus", tag:"🚀 MVP", intro:"Don't build everything at once. I'll help you identify the 3 core features that matter most, build them perfectly, and launch fast to get real user data.", price:"$900", hook:"What is the single core problem your app solves?" },
  { name:"Full Service", tag:"🎯 End-to-End", intro:"I handle everything: UI design, development, API integration, testing, and App Store submission. One person, one vision, zero handoff confusion.", price:"$1,600", hook:"Do you have designs ready, or do you need design work as well?" },
  { name:"Performance First", tag:"⚡ Performance", intro:"A slow app loses 50% of users. I optimize for speed, offline support, and smooth 60fps animations — because performance IS the product.", price:"$1,300", hook:"What devices and OS versions does your target audience primarily use?" },
  { name:"API Integration", tag:"🔗 Backend", intro:"I specialize in apps that talk to complex backends — REST APIs, Firebase, Supabase, payment gateways, maps, and real-time data. Complexity is my specialty.", price:"$1,450", hook:"What backend or API does your app need to connect to?" },
  { name:"Startup Focused", tag:"🌱 Startup", intro:"I've worked with 8 funded startups. I understand speed, pivots, and investor demos. I'll build something that impresses users AND investors.", price:"$1,250", hook:"Are you building this for investors to see, or for users to use — or both?" },
  { name:"Maintenance Plan", tag:"🔧 Long-term", intro:"Apps need updates. OS changes, new devices, and user feedback require ongoing work. I offer post-launch maintenance plans so your app stays healthy.", price:"$1,100", hook:"Do you have a plan for updates and maintenance after launch?" }
],

video: [
  { name:"YouTube Growth", tag:"📺 YouTube", intro:"I don't just edit videos — I edit for YouTube retention. Every cut, transition, and hook is designed to keep viewers watching until the end.", price:"$80/video", hook:"What's your current average view duration percentage?" },
  { name:"Reels & Shorts", tag:"📱 Short-form", intro:"Short-form content is the fastest way to grow. I create Reels and Shorts with pattern-interrupt edits that stop the scroll in the first 2 seconds.", price:"$45/video", hook:"What platform are you primarily targeting — Instagram, TikTok, or YouTube Shorts?" },
  { name:"Corporate Video", tag:"🏢 Corporate", intro:"Your brand video is often the first impression investors, clients, or partners get. I create polished, professional videos that build instant credibility.", price:"$150/video", hook:"What is the single message you want viewers to walk away with?" },
  { name:"Speed Delivery", tag:"⚡ 24hr", intro:"Send me your footage and reference style today. I'll deliver a fully edited, color-graded video within 24 hours — ready to post.", price:"$70/video", hook:"Do you have a specific reference video whose editing style you love?" },
  { name:"Social Proof", tag:"🏆 Results", intro:"A client's video I edited went from 800 views to 240,000 after I restructured the hook and pacing. The footage was the same — the editing changed everything.", price:"$90/video", hook:"What has performed best on your channel in the past?" },
  { name:"Color & Cinematic", tag:"🎨 Cinematic", intro:"Flat, ungraded footage looks amateur. I specialize in cinematic color grading that gives your videos a premium, film-like quality viewers immediately trust.", price:"$85/video", hook:"What mood or color palette do you want your brand videos to feel?" },
  { name:"Podcast Clips", tag:"🎙️ Podcast", intro:"Long podcasts become 10 viral clips. I find the gold moments, add captions, animations, and b-roll to create shareable content from every episode.", price:"$60/video", hook:"How long is each podcast episode and how many clips do you want per episode?" },
  { name:"Ad Creative", tag:"💰 Ads", intro:"I create video ads that convert. Hook in 3 seconds, problem in 10 seconds, solution in 20 seconds, CTA in 30 seconds. The formula works.", price:"$120/video", hook:"What platform is this ad for and what action should viewers take?" },
  { name:"Tutorial Videos", tag:"📚 Tutorial", intro:"Educational content builds authority and drives subscribers. I edit tutorials with clear annotations, zoom effects, and chapter markers for maximum learning.", price:"$75/video", hook:"Who is your target learner and what skill level are they at?" },
  { name:"Testimonial Edit", tag:"⭐ Testimonial", intro:"Customer testimonials are your most powerful sales tool. I edit raw testimonial footage into compelling 60-second videos that convert skeptics into buyers.", price:"$55/video", hook:"Do you have raw testimonial footage, or do you need help structuring the shoot?" }
],

data: [
  { name:"Business Intelligence", tag:"📊 BI", intro:"Raw data is noise. Insights are gold. I transform your spreadsheets into interactive dashboards that help you make decisions in minutes, not hours.", price:"$250", hook:"What's the one business question you most need your data to answer?" },
  { name:"Sales Analysis", tag:"💰 Sales", intro:"I specialize in sales funnel analysis — finding exactly where leads drop off and what changes would increase your revenue by 20-30%.", price:"$280", hook:"What's your biggest sales challenge that you think data could solve?" },
  { name:"Power BI Expert", tag:"📈 Power BI", intro:"I'll build you an interactive Power BI dashboard your entire team can use daily — no Excel skills required. Filters, drill-downs, and real-time updates.", price:"$320", hook:"Do you have Power BI Desktop, or do you need the full setup?" },
  { name:"Python Automation", tag:"🐍 Python", intro:"If you're doing the same Excel report manually every week, I'll write a Python script that does it in 30 seconds. Automation pays for itself in Week 1.", price:"$200", hook:"How many hours per week does your team spend on manual reporting?" },
  { name:"Social Media Analytics", tag:"📱 Social", intro:"Your social media data tells you exactly what content to create more of. I'll analyze your last 6 months of data and give you a clear content playbook.", price:"$180", hook:"Which platform's performance are you most trying to improve?" },
  { name:"eCommerce Analytics", tag:"🛒 eCommerce", intro:"I analyze your store's funnel — from traffic source to purchase — and tell you exactly which products, pages, and campaigns are making or losing you money.", price:"$290", hook:"What's your biggest eCommerce question — traffic, conversion, or retention?" },
  { name:"Predictive Model", tag:"🔮 Predictive", intro:"What if you could predict next month's revenue with 85% accuracy? I build predictive models that help businesses plan, not guess.", price:"$400", hook:"What business outcome would you most like to forecast?" },
  { name:"Data Cleaning", tag:"🧹 Clean", intro:"Dirty data gives wrong answers. Before any analysis, I'll clean, standardize, and validate your dataset so every insight you act on is trustworthy.", price:"$150", hook:"What format is your data currently in and how many rows are we talking?" },
  { name:"Google Analytics", tag:"📉 GA4", intro:"Most businesses have Google Analytics installed but don't understand what it's telling them. I'll set it up correctly AND explain the insights in plain English.", price:"$220", hook:"Do you have GA4 installed, or are you still on Universal Analytics?" },
  { name:"Survey Analysis", tag:"📋 Survey", intro:"Survey data is wasted if not analyzed correctly. I'll identify patterns, segment responses, and deliver a clear report with actionable recommendations.", price:"$170", hook:"How many survey responses do you have and what was the main research goal?" }
],

ecommerce: [
  { name:"Conversion Focus", tag:"💰 CRO", intro:"A beautiful store that doesn't convert is an expensive brochure. I build Shopify stores optimized for sales — every element tested and purposeful.", price:"$450", hook:"What's your current conversion rate and what would you like it to be?" },
  { name:"Launch Fast", tag:"⚡ Launch", intro:"I'll have your store live and taking orders within 5 days. Product pages, payment, shipping, and a home page that sells — all done.", price:"$380", hook:"Do you have product photos and descriptions ready, or do you need help?" },
  { name:"Social Proof Store", tag:"🏆 Trust", intro:"I build stores that earn trust: review widgets, trust badges, money-back guarantees, and social proof notifications — because trust is the #1 conversion factor.", price:"$420", hook:"Do you have existing customer reviews I can incorporate?" },
  { name:"Dropship Setup", tag:"📦 Dropship", intro:"I'll set up your dropshipping store end-to-end: supplier integration, product research, winning niche selection, and a store that scales.", price:"$350", hook:"Have you already selected your dropshipping supplier or niche?" },
  { name:"Migration Expert", tag:"🔄 Migration", intro:"Moving from WooCommerce to Shopify? Or Wix to WooCommerce? I handle migrations without losing products, SEO, or order history.", price:"$500", hook:"How many products, orders, and customer records need to be migrated?" },
  { name:"SEO Store", tag:"🔍 SEO", intro:"I build stores that rank. Every product title, description, and collection page is structured for Google — bringing you free organic traffic from day one.", price:"$480", hook:"What keywords do your ideal customers search before buying your products?" },
  { name:"Email Integration", tag:"📧 Email", intro:"The money is in the list. I'll set up your Klaviyo flows — abandoned cart, welcome series, and post-purchase — to recover 15-20% of lost sales automatically.", price:"$440", hook:"Do you have Klaviyo or Mailchimp set up, or do you need it from scratch?" },
  { name:"Amazon to Shopify", tag:"🔗 Multi-channel", intro:"Don't rely on Amazon alone. I'll build your Shopify store that syncs inventory with Amazon, letting you own your customer relationships.", price:"$520", hook:"Are you currently selling on Amazon, and do you want inventory to sync?" },
  { name:"Mobile Commerce", tag:"📱 Mobile", intro:"60% of eCommerce purchases happen on mobile. I build mobile-first stores where checkout takes 2 taps — because friction kills sales.", price:"$410", hook:"What percentage of your traffic is currently mobile vs desktop?" },
  { name:"Subscription Store", tag:"🔄 Subscriptions", intro:"Subscription businesses have 5x higher LTV than one-time stores. I'll set up your Shopify subscription model with Recharge — predictable revenue every month.", price:"$550", hook:"Have you thought about what subscription interval (weekly/monthly) works for your product?" }
]

}; // end TEMPLATE_DATA
